# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _pytrch
else:
    import _pytrch

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



TrchError = _pytrch.TrchError


def Boolean_List_marshal(inSize):
    return _pytrch.Boolean_List_marshal(inSize)

def Boolean_marshal(arg1):
    return _pytrch.Boolean_marshal(arg1)

def Boolean_type():
    return _pytrch.Boolean_type()

def Buffer_List_marshal(inSize):
    return _pytrch.Buffer_List_marshal(inSize)

def Buffer_marshal(inPtr):
    return _pytrch.Buffer_marshal(inPtr)

def Buffer_type():
    return _pytrch.Buffer_type()

def Config_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Config_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Config_delete(_self):
    return _pytrch.Config_delete(_self)

def Config_duplicate(_self):
    return _pytrch.Config_duplicate(_self)

def Config_getConfigVersion(_self):
    return _pytrch.Config_getConfigVersion(_self)

def Config_getConstants(_self, arg2):
    return _pytrch.Config_getConstants(_self, arg2)

def Config_getID(_self):
    return _pytrch.Config_getID(_self)

def Config_getInputParams(_self):
    return _pytrch.Config_getInputParams(_self)

def Config_getName(_self):
    return _pytrch.Config_getName(_self)

def Config_getNamespaceUri(_self):
    return _pytrch.Config_getNamespaceUri(_self)

def Config_getOutputParams(_self):
    return _pytrch.Config_getOutputParams(_self)

def Config_getSchemaVersion(_self):
    return _pytrch.Config_getSchemaVersion(_self)

def Config_getVersion(_self):
    return _pytrch.Config_getVersion(_self)

def Config_marshal(_self, arg2, arg3):
    return _pytrch.Config_marshal(_self, arg2, arg3)

def Config_printUsage(_self, arg2, arg3, arg4):
    return _pytrch.Config_printUsage(_self, arg2, arg3, arg4)

def Config_setConstants(_self, arg2):
    return _pytrch.Config_setConstants(_self, arg2)

def Config_setInputParams(_self, arg2):
    return _pytrch.Config_setInputParams(_self, arg2)

def Config_setOutputParams(_self, arg2):
    return _pytrch.Config_setOutputParams(_self, arg2)

def Config_unmarshal(str):
    return _pytrch.Config_unmarshal(str)

def FinalizeXMLUnmarshal():
    return _pytrch.FinalizeXMLUnmarshal()

def IPv4_List_marshal(inSize):
    return _pytrch.IPv4_List_marshal(inSize)

def IPv4_marshal(arg1):
    return _pytrch.IPv4_marshal(arg1)

def IPv4_type():
    return _pytrch.IPv4_type()

def IPv6_List_marshal(inSize):
    return _pytrch.IPv6_List_marshal(inSize)

def IPv6_marshal(arg1):
    return _pytrch.IPv6_marshal(arg1)

def IPv6_type():
    return _pytrch.IPv6_type()

def InitializeXMLUnmarshal():
    return _pytrch.InitializeXMLUnmarshal()

def List_format():
    return _pytrch.List_format()

def LocalFile_List_marshal(inSize):
    return _pytrch.LocalFile_List_marshal(inSize)

def LocalFile_marshal(arg1):
    return _pytrch.LocalFile_marshal(arg1)

def LocalFile_type():
    return _pytrch.LocalFile_type()

def Paramchoice_addParamgroup(_self, arg2):
    return _pytrch.Paramchoice_addParamgroup(_self, arg2)

def Paramchoice_create(arg1, arg2, arg3, arg4, arg5):
    return _pytrch.Paramchoice_create(arg1, arg2, arg3, arg4, arg5)

def Paramchoice_delete(_self):
    return _pytrch.Paramchoice_delete(_self)

def Paramchoice_getDefaultValue(_self):
    return _pytrch.Paramchoice_getDefaultValue(_self)

def Paramchoice_getDescription(_self):
    return _pytrch.Paramchoice_getDescription(_self)

def Paramchoice_getName(_self):
    return _pytrch.Paramchoice_getName(_self)

def Paramchoice_getNumParamgroups(_self):
    return _pytrch.Paramchoice_getNumParamgroups(_self)

def Paramchoice_getParamgroup(_self, arg2):
    return _pytrch.Paramchoice_getParamgroup(_self, arg2)

def Paramchoice_getValue(_self):
    return _pytrch.Paramchoice_getValue(_self)

def Paramchoice_hasValidValue(_self):
    return _pytrch.Paramchoice_hasValidValue(_self)

def Paramchoice_hasValue(_self):
    return _pytrch.Paramchoice_hasValue(_self)

def Paramchoice_isValid(_self):
    return _pytrch.Paramchoice_isValid(_self)

def Paramchoice_matchName(_self, arg2):
    return _pytrch.Paramchoice_matchName(_self, arg2)

def Paramchoice_setValue(_self, arg2):
    return _pytrch.Paramchoice_setValue(_self, arg2)

def Parameter_Boolean_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_Boolean_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_Boolean_List_getSize(_self):
    return _pytrch.Parameter_Boolean_List_getSize(_self)

def Parameter_Boolean_List_getValue(_self):
    return _pytrch.Parameter_Boolean_List_getValue(_self)

def Parameter_Boolean_List_setValue(_self, inSize):
    return _pytrch.Parameter_Boolean_List_setValue(_self, inSize)

def Parameter_Boolean_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_Boolean_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_Boolean_getValue(_self):
    return _pytrch.Parameter_Boolean_getValue(_self)

def Parameter_Boolean_setValue(_self, arg2):
    return _pytrch.Parameter_Boolean_setValue(_self, arg2)

def Parameter_Buffer_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_Buffer_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_Buffer_List_getSize(_self):
    return _pytrch.Parameter_Buffer_List_getSize(_self)

def Parameter_Buffer_List_getValue(_self):
    return _pytrch.Parameter_Buffer_List_getValue(_self)

def Parameter_Buffer_List_setValue(_self, inSize):
    return _pytrch.Parameter_Buffer_List_setValue(_self, inSize)

def Parameter_Buffer_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_Buffer_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_Buffer_getValue(_self):
    return _pytrch.Parameter_Buffer_getValue(_self)

def Parameter_Buffer_setValue(_self, inPtr):
    return _pytrch.Parameter_Buffer_setValue(_self, inPtr)

def Parameter_IPv4_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_IPv4_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_IPv4_List_getSize(_self):
    return _pytrch.Parameter_IPv4_List_getSize(_self)

def Parameter_IPv4_List_getValue(_self):
    return _pytrch.Parameter_IPv4_List_getValue(_self)

def Parameter_IPv4_List_setValue(_self, inSize):
    return _pytrch.Parameter_IPv4_List_setValue(_self, inSize)

def Parameter_IPv4_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_IPv4_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_IPv4_getValue(_self):
    return _pytrch.Parameter_IPv4_getValue(_self)

def Parameter_IPv4_setValue(_self, arg2):
    return _pytrch.Parameter_IPv4_setValue(_self, arg2)

def Parameter_IPv6_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_IPv6_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_IPv6_List_getSize(_self):
    return _pytrch.Parameter_IPv6_List_getSize(_self)

def Parameter_IPv6_List_getValue(_self):
    return _pytrch.Parameter_IPv6_List_getValue(_self)

def Parameter_IPv6_List_setValue(_self, inSize):
    return _pytrch.Parameter_IPv6_List_setValue(_self, inSize)

def Parameter_IPv6_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_IPv6_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_IPv6_getValue(_self):
    return _pytrch.Parameter_IPv6_getValue(_self)

def Parameter_IPv6_setValue(_self, arg2):
    return _pytrch.Parameter_IPv6_setValue(_self, arg2)

def Parameter_LocalFile_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_LocalFile_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_LocalFile_List_getSize(_self):
    return _pytrch.Parameter_LocalFile_List_getSize(_self)

def Parameter_LocalFile_List_getValue(_self):
    return _pytrch.Parameter_LocalFile_List_getValue(_self)

def Parameter_LocalFile_List_setValue(_self, inSize):
    return _pytrch.Parameter_LocalFile_List_setValue(_self, inSize)

def Parameter_LocalFile_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_LocalFile_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_LocalFile_getValue(_self):
    return _pytrch.Parameter_LocalFile_getValue(_self)

def Parameter_LocalFile_setValue(_self, arg2):
    return _pytrch.Parameter_LocalFile_setValue(_self, arg2)

def Parameter_Port_List_getSize(_self):
    return _pytrch.Parameter_Port_List_getSize(_self)

def Parameter_Port_List_getValue(_self):
    return _pytrch.Parameter_Port_List_getValue(_self)

def Parameter_Port_List_setValue(_self, inSize):
    return _pytrch.Parameter_Port_List_setValue(_self, inSize)

def Parameter_Port_getValue(_self):
    return _pytrch.Parameter_Port_getValue(_self)

def Parameter_Port_setValue(_self, arg2):
    return _pytrch.Parameter_Port_setValue(_self, arg2)

def Parameter_S16_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_S16_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_S16_List_getSize(_self):
    return _pytrch.Parameter_S16_List_getSize(_self)

def Parameter_S16_List_getValue(_self):
    return _pytrch.Parameter_S16_List_getValue(_self)

def Parameter_S16_List_setValue(_self, inSize):
    return _pytrch.Parameter_S16_List_setValue(_self, inSize)

def Parameter_S16_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_S16_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_S16_getValue(_self):
    return _pytrch.Parameter_S16_getValue(_self)

def Parameter_S16_setValue(_self, arg2):
    return _pytrch.Parameter_S16_setValue(_self, arg2)

def Parameter_S32_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_S32_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_S32_List_getSize(_self):
    return _pytrch.Parameter_S32_List_getSize(_self)

def Parameter_S32_List_getValue(_self):
    return _pytrch.Parameter_S32_List_getValue(_self)

def Parameter_S32_List_setValue(_self, inSize):
    return _pytrch.Parameter_S32_List_setValue(_self, inSize)

def Parameter_S32_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_S32_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_S32_getValue(_self):
    return _pytrch.Parameter_S32_getValue(_self)

def Parameter_S32_setValue(_self, arg2):
    return _pytrch.Parameter_S32_setValue(_self, arg2)

def Parameter_S64_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_S64_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_S64_List_getSize(_self):
    return _pytrch.Parameter_S64_List_getSize(_self)

def Parameter_S64_List_getValue(_self):
    return _pytrch.Parameter_S64_List_getValue(_self)

def Parameter_S64_List_setValue(_self, inSize):
    return _pytrch.Parameter_S64_List_setValue(_self, inSize)

def Parameter_S64_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_S64_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_S64_getValue(_self):
    return _pytrch.Parameter_S64_getValue(_self)

def Parameter_S64_setValue(_self, arg2):
    return _pytrch.Parameter_S64_setValue(_self, arg2)

def Parameter_S8_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_S8_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_S8_List_getSize(_self):
    return _pytrch.Parameter_S8_List_getSize(_self)

def Parameter_S8_List_getValue(_self):
    return _pytrch.Parameter_S8_List_getValue(_self)

def Parameter_S8_List_setValue(_self, inSize):
    return _pytrch.Parameter_S8_List_setValue(_self, inSize)

def Parameter_S8_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_S8_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_S8_getValue(_self):
    return _pytrch.Parameter_S8_getValue(_self)

def Parameter_S8_setValue(_self, arg2):
    return _pytrch.Parameter_S8_setValue(_self, arg2)

def Parameter_Socket_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_Socket_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_Socket_List_getSize(_self):
    return _pytrch.Parameter_Socket_List_getSize(_self)

def Parameter_Socket_List_getValue(_self):
    return _pytrch.Parameter_Socket_List_getValue(_self)

def Parameter_Socket_List_setValue(_self, inSize):
    return _pytrch.Parameter_Socket_List_setValue(_self, inSize)

def Parameter_Socket_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_Socket_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_Socket_getValue(_self):
    return _pytrch.Parameter_Socket_getValue(_self)

def Parameter_Socket_setValue(_self, arg2):
    return _pytrch.Parameter_Socket_setValue(_self, arg2)

def Parameter_String_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_String_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_String_List_getSize(_self):
    return _pytrch.Parameter_String_List_getSize(_self)

def Parameter_String_List_getValue(_self):
    return _pytrch.Parameter_String_List_getValue(_self)

def Parameter_String_List_setValue(_self, inSize):
    return _pytrch.Parameter_String_List_setValue(_self, inSize)

def Parameter_String_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_String_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_String_getValue(_self):
    return _pytrch.Parameter_String_getValue(_self)

def Parameter_String_setValue(_self, arg2):
    return _pytrch.Parameter_String_setValue(_self, arg2)

def Parameter_TcpPort_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_TcpPort_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_TcpPort_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_TcpPort_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_U16_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_U16_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_U16_List_getSize(_self):
    return _pytrch.Parameter_U16_List_getSize(_self)

def Parameter_U16_List_getValue(_self):
    return _pytrch.Parameter_U16_List_getValue(_self)

def Parameter_U16_List_setValue(_self, inSize):
    return _pytrch.Parameter_U16_List_setValue(_self, inSize)

def Parameter_U16_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_U16_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_U16_getValue(_self):
    return _pytrch.Parameter_U16_getValue(_self)

def Parameter_U16_setValue(_self, arg2):
    return _pytrch.Parameter_U16_setValue(_self, arg2)

def Parameter_U32_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_U32_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_U32_List_getSize(_self):
    return _pytrch.Parameter_U32_List_getSize(_self)

def Parameter_U32_List_getValue(_self):
    return _pytrch.Parameter_U32_List_getValue(_self)

def Parameter_U32_List_setValue(_self, inSize):
    return _pytrch.Parameter_U32_List_setValue(_self, inSize)

def Parameter_U32_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_U32_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_U32_getValue(_self):
    return _pytrch.Parameter_U32_getValue(_self)

def Parameter_U32_setValue(_self, arg2):
    return _pytrch.Parameter_U32_setValue(_self, arg2)

def Parameter_U64_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_U64_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_U64_List_getSize(_self):
    return _pytrch.Parameter_U64_List_getSize(_self)

def Parameter_U64_List_getValue(_self):
    return _pytrch.Parameter_U64_List_getValue(_self)

def Parameter_U64_List_setValue(_self, inSize):
    return _pytrch.Parameter_U64_List_setValue(_self, inSize)

def Parameter_U64_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_U64_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_U64_getValue(_self):
    return _pytrch.Parameter_U64_getValue(_self)

def Parameter_U64_setValue(_self, arg2):
    return _pytrch.Parameter_U64_setValue(_self, arg2)

def Parameter_U8_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_U8_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_U8_List_getSize(_self):
    return _pytrch.Parameter_U8_List_getSize(_self)

def Parameter_U8_List_getValue(_self):
    return _pytrch.Parameter_U8_List_getValue(_self)

def Parameter_U8_List_setValue(_self, inSize):
    return _pytrch.Parameter_U8_List_setValue(_self, inSize)

def Parameter_U8_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_U8_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_U8_getValue(_self):
    return _pytrch.Parameter_U8_getValue(_self)

def Parameter_U8_setValue(_self, arg2):
    return _pytrch.Parameter_U8_setValue(_self, arg2)

def Parameter_UString_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_UString_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_UString_List_getSize(_self):
    return _pytrch.Parameter_UString_List_getSize(_self)

def Parameter_UString_List_getValue(_self):
    return _pytrch.Parameter_UString_List_getValue(_self)

def Parameter_UString_List_setValue(_self, inSize):
    return _pytrch.Parameter_UString_List_setValue(_self, inSize)

def Parameter_UString_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_UString_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_UString_getValue(_self):
    return _pytrch.Parameter_UString_getValue(_self)

def Parameter_UString_setValue(_self, inPtr):
    return _pytrch.Parameter_UString_setValue(_self, inPtr)

def Parameter_UdpPort_List_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_UdpPort_List_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_UdpPort_create(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pytrch.Parameter_UdpPort_create(arg1, arg2, arg3, arg4, arg5, arg6)

def Parameter_delete(_self):
    return _pytrch.Parameter_delete(_self)

def Parameter_getDescription(_self):
    return _pytrch.Parameter_getDescription(_self)

def Parameter_getFormat(_self):
    return _pytrch.Parameter_getFormat(_self)

def Parameter_getInvalidReason(_self, arg2):
    return _pytrch.Parameter_getInvalidReason(_self, arg2)

def Parameter_getMarshalledDefault(_self):
    return _pytrch.Parameter_getMarshalledDefault(_self)

def Parameter_getMarshalledValue(_self):
    return _pytrch.Parameter_getMarshalledValue(_self)

def Parameter_getName(_self):
    return _pytrch.Parameter_getName(_self)

def Parameter_getType(_self):
    return _pytrch.Parameter_getType(_self)

def Parameter_hasValidValue(_self):
    return _pytrch.Parameter_hasValidValue(_self)

def Parameter_hasValue(_self):
    return _pytrch.Parameter_hasValue(_self)

def Parameter_hide(_self):
    return _pytrch.Parameter_hide(_self)

def Parameter_isHidden(_self):
    return _pytrch.Parameter_isHidden(_self)

def Parameter_isRequired(_self):
    return _pytrch.Parameter_isRequired(_self)

def Parameter_isValid(_self):
    return _pytrch.Parameter_isValid(_self)

def Parameter_markInvalid(_self):
    return _pytrch.Parameter_markInvalid(_self)

def Parameter_markInvalidWithReason(_self, arg2):
    return _pytrch.Parameter_markInvalidWithReason(_self, arg2)

def Parameter_matchFormat(_self, arg2):
    return _pytrch.Parameter_matchFormat(_self, arg2)

def Parameter_matchFormatAndType(_self, arg2, arg3):
    return _pytrch.Parameter_matchFormatAndType(_self, arg2, arg3)

def Parameter_matchName(_self, arg2):
    return _pytrch.Parameter_matchName(_self, arg2)

def Parameter_matchType(_self, arg2):
    return _pytrch.Parameter_matchType(_self, arg2)

def Parameter_resetValue(_self):
    return _pytrch.Parameter_resetValue(_self)

def Parameter_setMarshalledValue(_self, arg2):
    return _pytrch.Parameter_setMarshalledValue(_self, arg2)

def Paramgroup_addParamchoice(_self, arg2):
    return _pytrch.Paramgroup_addParamchoice(_self, arg2)

def Paramgroup_addParameter(_self, arg2):
    return _pytrch.Paramgroup_addParameter(_self, arg2)

def Paramgroup_create(arg1, arg2, arg3, arg4):
    return _pytrch.Paramgroup_create(arg1, arg2, arg3, arg4)

def Paramgroup_delete(_self):
    return _pytrch.Paramgroup_delete(_self)

def Paramgroup_getDescription(_self):
    return _pytrch.Paramgroup_getDescription(_self)

def Paramgroup_getName(_self):
    return _pytrch.Paramgroup_getName(_self)

def Paramgroup_getNumParamchoices(_self):
    return _pytrch.Paramgroup_getNumParamchoices(_self)

def Paramgroup_getNumParameters(_self):
    return _pytrch.Paramgroup_getNumParameters(_self)

def Paramgroup_getParamchoice(_self, arg2):
    return _pytrch.Paramgroup_getParamchoice(_self, arg2)

def Paramgroup_getParameter(_self, arg2):
    return _pytrch.Paramgroup_getParameter(_self, arg2)

def Paramgroup_isValid(_self):
    return _pytrch.Paramgroup_isValid(_self)

def Paramgroup_matchName(_self, arg2):
    return _pytrch.Paramgroup_matchName(_self, arg2)

def Paramgroup_removeParameter(_self, arg2):
    return _pytrch.Paramgroup_removeParameter(_self, arg2)

def Params_addParamchoice(_self, arg2):
    return _pytrch.Params_addParamchoice(_self, arg2)

def Params_addParameter(_self, arg2):
    return _pytrch.Params_addParameter(_self, arg2)

def Params_create(arg1, arg2, arg3):
    return _pytrch.Params_create(arg1, arg2, arg3)

def Params_delete(_self):
    return _pytrch.Params_delete(_self)

def Params_duplicate(_self):
    return _pytrch.Params_duplicate(_self)

def Params_findParamchoice(_self, arg2):
    return _pytrch.Params_findParamchoice(_self, arg2)

def Params_findParameter(_self, arg2):
    return _pytrch.Params_findParameter(_self, arg2)

def Params_getCallbackIPv4Values(_self, arg2, arg3, arg4, arg5):
    return _pytrch.Params_getCallbackIPv4Values(_self, arg2, arg3, arg4, arg5)

def Params_getCallbackIPv6Values(_self, arg2, arg3, arg4, arg5):
    return _pytrch.Params_getCallbackIPv6Values(_self, arg2, arg3, arg4, arg5)

def Params_getCallbackPortValues(_self, arg2, arg3, arg4, arg5):
    return _pytrch.Params_getCallbackPortValues(_self, arg2, arg3, arg4, arg5)

def Params_getName(_self):
    return _pytrch.Params_getName(_self)

def Params_getNumParamchoices(_self):
    return _pytrch.Params_getNumParamchoices(_self)

def Params_getNumParameters(_self):
    return _pytrch.Params_getNumParameters(_self)

def Params_getParamchoice(_self, arg2):
    return _pytrch.Params_getParamchoice(_self, arg2)

def Params_getParameter(_self, arg2):
    return _pytrch.Params_getParameter(_self, arg2)

def Params_isValid(_self):
    return _pytrch.Params_isValid(_self)

def Params_parseCommandLine(_self, arg2, arg3, arg4):
    return _pytrch.Params_parseCommandLine(_self, arg2, arg3, arg4)

def Params_printInvalid(_self, arg2):
    return _pytrch.Params_printInvalid(_self, arg2)

def Params_removeParameter(_self, arg2):
    return _pytrch.Params_removeParameter(_self, arg2)

def Params_validateCallbackPorts(_self, arg2, arg3):
    return _pytrch.Params_validateCallbackPorts(_self, arg2, arg3)

def Port_List_marshal(inSize):
    return _pytrch.Port_List_marshal(inSize)

def Port_marshal(arg1):
    return _pytrch.Port_marshal(arg1)

def S16_List_marshal(inSize):
    return _pytrch.S16_List_marshal(inSize)

def S16_marshal(arg1):
    return _pytrch.S16_marshal(arg1)

def S16_type():
    return _pytrch.S16_type()

def S32_List_marshal(inSize):
    return _pytrch.S32_List_marshal(inSize)

def S32_marshal(arg1):
    return _pytrch.S32_marshal(arg1)

def S32_type():
    return _pytrch.S32_type()

def S64_List_marshal(inSize):
    return _pytrch.S64_List_marshal(inSize)

def S64_marshal(arg1):
    return _pytrch.S64_marshal(arg1)

def S64_type():
    return _pytrch.S64_type()

def S8_List_marshal(inSize):
    return _pytrch.S8_List_marshal(inSize)

def S8_marshal(arg1):
    return _pytrch.S8_marshal(arg1)

def S8_type():
    return _pytrch.S8_type()

def Scalar_format():
    return _pytrch.Scalar_format()

def Socket_List_marshal(inSize):
    return _pytrch.Socket_List_marshal(inSize)

def Socket_marshal(arg1):
    return _pytrch.Socket_marshal(arg1)

def Socket_type():
    return _pytrch.Socket_type()

def String_List_marshal(inSize):
    return _pytrch.String_List_marshal(inSize)

def String_marshal(arg1):
    return _pytrch.String_marshal(arg1)

def String_type():
    return _pytrch.String_type()

def TcpPort_type():
    return _pytrch.TcpPort_type()

def U16_List_marshal(inSize):
    return _pytrch.U16_List_marshal(inSize)

def U16_marshal(arg1):
    return _pytrch.U16_marshal(arg1)

def U16_type():
    return _pytrch.U16_type()

def U32_List_marshal(inSize):
    return _pytrch.U32_List_marshal(inSize)

def U32_marshal(arg1):
    return _pytrch.U32_marshal(arg1)

def U32_type():
    return _pytrch.U32_type()

def U64_List_marshal(inSize):
    return _pytrch.U64_List_marshal(inSize)

def U64_marshal(arg1):
    return _pytrch.U64_marshal(arg1)

def U64_type():
    return _pytrch.U64_type()

def U8_List_marshal(inSize, inptr):
    return _pytrch.U8_List_marshal(inSize, inptr)

def U8_marshal(arg1):
    return _pytrch.U8_marshal(arg1)

def U8_type():
    return _pytrch.U8_type()

def UString_List_marshal(inSize):
    return _pytrch.UString_List_marshal(inSize)

def UString_marshal(inPtr):
    return _pytrch.UString_marshal(inPtr)

def UString_type():
    return _pytrch.UString_type()

def UdpPort_type():
    return _pytrch.UdpPort_type()

def freeMarshalledValue(arg1):
    return _pytrch.freeMarshalledValue(arg1)

def fuck1():
    return _pytrch.fuck1()

def fuck2():
    return _pytrch.fuck2()

def fuck3():
    return _pytrch.fuck3()

def fuck4():
    return _pytrch.fuck4()

def fuck5():
    return _pytrch.fuck5()

def fuck6():
    return _pytrch.fuck6()

def fuck7():
    return _pytrch.fuck7()

def fuck8():
    return _pytrch.fuck8()


